// <auto-generated />
using System;
using Cortez_Enzo_Evaluacion_P_I.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cortez_Enzo_Evaluacion_P_I.Migrations
{
    [DbContext(typeof(Cortez_Enzo_Evaluacion_P_IContext))]
    partial class Cortez_Enzo_Evaluacion_P_IContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cortez_Enzo_Evaluacion_P_I.Models.Celular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Año")
                        .HasColumnType("date");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("Cortez_Enzo_Evaluacion_P_I.Models.ECortez", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cedula"));

                    b.Property<int?>("CelularId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Cummpleaños")
                        .HasColumnType("date");

                    b.Property<bool>("Estudiante")
                        .HasColumnType("bit");

                    b.Property<double>("Mesada")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Cedula");

                    b.HasIndex("CelularId");

                    b.ToTable("ECortez");
                });

            modelBuilder.Entity("Cortez_Enzo_Evaluacion_P_I.Models.ECortez", b =>
                {
                    b.HasOne("Cortez_Enzo_Evaluacion_P_I.Models.Celular", "Celular")
                        .WithMany()
                        .HasForeignKey("CelularId");

                    b.Navigation("Celular");
                });
#pragma warning restore 612, 618
        }
    }
}
